"""
PACTS Generated Test
====================
Requirement ID: github_search
Generated: 2025-11-01 20:40:45
Verdict: PASS

Discovery Strategies Used:
  - placeholder

"""

import asyncio
from playwright.async_api import async_playwright


async def test_github_search():
    """
    Test for requirement: github_search

    Test Details:
    - URL: https://github.com
    - Steps: 2
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://github.com")

        # Step 1: FILL Search
        # Selector: [placeholder*="Search or jump to..."]
        # Strategy: placeholder, Confidence: 0.88
        await page.locator("[placeholder*="Search or jump to..."]").fill("playwright")
        # Step 2: PRESS Search
        # Selector: [placeholder*="Search or jump to..."]
        # Strategy: placeholder, Confidence: 0.88
        await page.locator("[placeholder*="Search or jump to..."]").press("Enter")
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_github_search())