"""
PACTS Generated Test
====================
Requirement ID: salesforce_opportunity_postlogin
Generated: 2025-11-02 16:13:20
Verdict: PASS

Discovery Strategies Used:
  - label
  - role_name
  - role_name_disambiguated

"""

import asyncio
from playwright.async_api import async_playwright


async def test_salesforce_opportunity_postlogin():
    """
    Test for requirement: salesforce_opportunity_postlogin

    Test Details:
    - URL: https://orgfarm-9a1de3d5e8-dev-ed.develop.lightning.force.com/lightning/o/Opportunity/list
    - Steps: 10
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://orgfarm-9a1de3d5e8-dev-ed.develop.lightning.force.com/lightning/o/Opportunity/list")

        # Step 1: CLICK New
        # Selector: role=button[name*="new"i]
        # Strategy: role_name, Confidence: 0.95
        await page.locator("role=button[name*="new"i]").click()
        # Step 2: FILL Opportunity Name
        # Selector: #input-277
        # Strategy: label, Confidence: 0.92
        await page.locator("#input-277").fill("Q1 2025 Enterprise Deal")
        # Step 3: FILL Amount
        # Selector: #input-262
        # Strategy: label, Confidence: 0.92
        await page.locator("#input-262").fill("100000")
        # Step 4: CLICK Stage
        # Selector: #combobox-button-291
        # Strategy: label, Confidence: 0.92
        await page.locator("#combobox-button-291").click()
        # Step 5: SELECT Stage
        # Selector: #combobox-button-291
        # Strategy: label, Confidence: 0.92
        await page.locator("#combobox-button-291").select_option("Prospecting")
        # Step 6: FILL Close Date
        # Selector: #input-270
        # Strategy: label, Confidence: 0.92
        await page.locator("#input-270").fill("12/31/2025")
        # Step 7: FILL RAI Test Score
        # Selector: #input-320
        # Strategy: label, Confidence: 0.92
        await page.locator("#input-320").fill("75")
        # Step 8: CLICK RAI Priority Level
        # Selector: #combobox-button-334
        # Strategy: label, Confidence: 0.92
        await page.locator("#combobox-button-334").click()
        # Step 9: SELECT RAI Priority Level
        # Selector: #combobox-button-334
        # Strategy: label, Confidence: 0.92
        await page.locator("#combobox-button-334").select_option("Low")
        # Step 10: CLICK Save
        # Selector: role=button[name*="save"i] >> nth=0
        # Strategy: role_name_disambiguated, Confidence: 0.95
        await page.locator("role=button[name*="save"i] >> nth=0").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_salesforce_opportunity_postlogin())