"""
PACTS Generated Test
====================
Requirement ID: reddit_search
Generated: 2025-11-01 00:58:09
Verdict: PASS

Discovery Strategies Used:
  - mcp_direct_action

"""

import asyncio
from playwright.async_api import async_playwright


async def test_reddit_search():
    """
    Test for requirement: reddit_search

    Test Details:
    - URL: https://www.reddit.com
    - Steps: 5
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.reddit.com")

        # Step 1: FILL Search
        # Selector: MCP_FILL:Search
        # Strategy: mcp_direct_action, Confidence: 0.95
        await page.locator("MCP_FILL:Search").fill("programming")
        # Step 2: PRESS Search
        # Selector: MCP_FILL:Search
        # Strategy: mcp_direct_action, Confidence: 0.95
        await page.locator("MCP_FILL:Search").press("Enter")
        # Step 3: CLICK Communities
        # Selector: MCP_CLICK:Communities
        # Strategy: mcp_direct_action, Confidence: 0.95
        await page.locator("MCP_CLICK:Communities").click()
        # Step 4: CLICK r/programming
        # Selector: MCP_CLICK:r/programming
        # Strategy: mcp_direct_action, Confidence: 0.95
        await page.locator("MCP_CLICK:r/programming").click()
        # Step 5: CLICK Hot
        # Selector: MCP_CLICK:Hot
        # Strategy: mcp_direct_action, Confidence: 0.95
        await page.locator("MCP_CLICK:Hot").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_reddit_search())