"""
PACTS Generated Test
====================
Requirement ID: github_search
Generated: 2025-11-09 02:11:28
Verdict: PASS

Discovery Strategies Used:
  - aria_label_scoped

"""

import asyncio
from playwright.async_api import async_playwright


async def test_github_search():
    """
    Test for requirement: github_search

    Test Details:
    - URL: https://github.com
    - Steps: 2
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://github.com")

        # Step 1: FILL Search
        # Selector: input[name="query-builder-test"]
        # Strategy: aria_label_scoped, Confidence: 0.98
        await page.locator("input[name="query-builder-test"]").fill("playwright")
        # Step 2: PRESS Search
        # Selector: input[name="query-builder-test"]
        # Strategy: aria_label_scoped, Confidence: 0.98
        await page.locator("input[name="query-builder-test"]").press("Enter")
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_github_search())