"""
PACTS Generated Test
====================
Requirement ID: youtube_search
Generated: 2025-11-09 02:17:52
Verdict: PASS

Discovery Strategies Used:
  - placeholder_attr
  - youtube_video

"""

import asyncio
from playwright.async_api import async_playwright


async def test_youtube_search():
    """
    Test for requirement: youtube_search

    Test Details:
    - URL: https://www.youtube.com
    - Steps: 3
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.youtube.com")

        # Step 1: FILL Search
        # Selector: input[placeholder="Search"]
        # Strategy: placeholder_attr, Confidence: 0.9
        await page.locator("input[placeholder="Search"]").fill("Playwright automation tutorial")
        # Step 2: PRESS Search
        # Selector: input[placeholder="Search"]
        # Strategy: placeholder_attr, Confidence: 0.9
        await page.locator("input[placeholder="Search"]").press("Enter")
        # Step 3: CLICK Video
        # Selector: a#video-title >> nth=0
        # Strategy: youtube_video, Confidence: 0.94
        await page.locator("a#video-title >> nth=0").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_youtube_search())