"""
PACTS Generated Test
====================
Requirement ID: healed_test_example
Generated: 2025-10-30 21:21:58
Verdict: PASS (HEALED: 1 rounds)

Discovery Strategies Used:
  - placeholder
  - role_name

"""

import asyncio
from playwright.async_api import async_playwright


async def test_healed_test_example():
    """
    Test for requirement: healed_test_example

    Test Details:
    - URL: https://example.com
    - Steps: 2
    - Verdict: pass
    - Healed: Yes (1 rounds)

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://example.com")

        # Step 1: FILL Username
        # Selector: #username
        # Strategy: placeholder, Confidence: 0.88
        await page.locator("#username").fill("testuser")
        # Step 2: CLICK Submit
        # Selector: #submit-btn
        # Strategy: role_name, Confidence: 0.95
        # HEALED: Round 1, Strategy: reveal
        await page.locator("#submit-btn").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_healed_test_example())