"""
PACTS Generated Test
====================
Requirement ID: amazon_search
Generated: 2025-11-01 01:28:16
Verdict: PASS (HEALED: 3 rounds)

Discovery Strategies Used:
  - failed

"""

import asyncio
from playwright.async_api import async_playwright


async def test_amazon_search():
    """
    Test for requirement: amazon_search

    Test Details:
    - URL: https://www.amazon.com
    - Steps: 2
    - Verdict: pass
    - Healed: Yes (3 rounds)

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.amazon.com")

        # Step 1: FILL Search
        # Selector: input[id*="search"]
        # Strategy: failed, Confidence: 0.0
        # HEALED: Round 3, Strategy: reprobe:fallback_css
        await page.locator("input[id*="search"]").fill("laptop")
        # Step 2: PRESS Search
        # Selector: input[id*="search"]
        # Strategy: failed, Confidence: 0.0
        await page.locator("input[id*="search"]").press("Enter")
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_amazon_search())