"""
PACTS Generated Test
====================
Requirement ID: booking_search.txt
Generated: 2025-11-09 02:54:50
Verdict: FAIL

Discovery Strategies Used:
  - booking_destination_canonical
  - failed

"""

import asyncio
from playwright.async_api import async_playwright


async def test_booking_search_txt():
    """
    Test for requirement: booking_search.txt

    Test Details:
    - URL: https://www.booking.com
    - Steps: 3
    - Verdict: fail
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.booking.com")

        # Step 1: FILL Destination
        # Selector: input[name="ss"]
        # Strategy: booking_destination_canonical, Confidence: 0.96
        await page.locator("input[name="ss"]").fill("Paris")
        # Step 2: CLICK Autocomplete
        # Selector: DISCOVERY_FAILED
        # Strategy: failed, Confidence: 0.0
        await page.locator("DISCOVERY_FAILED").click()
        # Step 3: CLICK Search
        # Selector: 
        # Strategy: , Confidence: 
        await page.locator("").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_booking_search_txt())