"""
PACTS Generated Test
====================
Requirement ID: metadata_test
Generated: 2025-10-30 21:21:58
Verdict: PASS

Discovery Strategies Used:
  - role_name

"""

import asyncio
from playwright.async_api import async_playwright


async def test_metadata_test():
    """
    Test for requirement: metadata_test

    Test Details:
    - URL: https://example.com
    - Steps: 1
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://example.com")

        # Step 1: CLICK TestButton
        # Selector: #test-btn
        # Strategy: role_name, Confidence: 0.9
        await page.locator("#test-btn").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_metadata_test())