"""
PACTS Generated Test
====================
Requirement ID: booking_search
Generated: 2025-11-09 02:06:57
Verdict: BLOCKED

Discovery Strategies Used:
  - failed

"""

import asyncio
from playwright.async_api import async_playwright


async def test_booking_search():
    """
    Test for requirement: booking_search

    Test Details:
    - URL: https://www.booking.com
    - Steps: 3
    - Verdict: BLOCKED
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.booking.com")

        # Step 1: FILL Destination
        # Selector: DISCOVERY_FAILED
        # Strategy: failed, Confidence: 0.0
        await page.locator("DISCOVERY_FAILED").fill("Paris")
        # Step 2: CLICK Autocomplete
        # Selector: 
        # Strategy: , Confidence: 
        await page.locator("").click()
        # Step 3: CLICK Search
        # Selector: 
        # Strategy: , Confidence: 
        await page.locator("").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_booking_search())