"""
PACTS Generated Test
====================
Requirement ID: booking_search
Generated: 2025-11-09 02:38:52
Verdict: FAIL

Discovery Strategies Used:
  - booking_destination_combobox
  - failed

"""

import asyncio
from playwright.async_api import async_playwright


async def test_booking_search():
    """
    Test for requirement: booking_search

    Test Details:
    - URL: https://www.booking.com
    - Steps: 3
    - Verdict: fail
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.booking.com")

        # Step 1: FILL Destination
        # Selector: role=combobox[name=/destination|where are you going/i]
        # Strategy: booking_destination_combobox, Confidence: 0.94
        await page.locator("role=combobox[name=/destination|where are you going/i]").fill("Paris")
        # Step 2: CLICK Autocomplete
        # Selector: [data-testid*="autocomplete"]
        # Strategy: failed, Confidence: 0.0
        await page.locator("[data-testid*="autocomplete"]").click()
        # Step 3: CLICK Search
        # Selector: 
        # Strategy: , Confidence: 
        await page.locator("").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_booking_search())