"""
PACTS Generated Test
====================
Requirement ID: salesforce_login
Generated: 2025-10-31 22:50:41
Verdict: PASS

Discovery Strategies Used:
  - label
  - role_name

"""

import asyncio
from playwright.async_api import async_playwright


async def test_salesforce_login():
    """
    Test for requirement: salesforce_login

    Test Details:
    - URL: https://orgfarm-9a1de3d5e8-dev-ed.develop.my.salesforce.com
    - Steps: 3
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://orgfarm-9a1de3d5e8-dev-ed.develop.my.salesforce.com")

        # Step 1: FILL Username
        # Selector: #username
        # Strategy: label, Confidence: 0.92
        await page.locator("#username").fill("debashishroy00106@agentforce.com")
        # Step 2: FILL Password
        # Selector: #password
        # Strategy: label, Confidence: 0.92
        await page.locator("#password").fill("Pink12345678")
        # Step 3: CLICK Log In
        # Selector: #Login
        # Strategy: role_name, Confidence: 0.95
        await page.locator("#Login").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_salesforce_login())