"""
PACTS Generated Test
====================
Requirement ID: login_simple
Generated: 2025-11-09 01:28:21
Verdict: PASS

Discovery Strategies Used:
  - name_attr_fuzzy
  - placeholder_attr
  - role_name
  - role_name_nth_locator

"""

import asyncio
from playwright.async_api import async_playwright


async def test_login_simple():
    """
    Test for requirement: login_simple

    Test Details:
    - URL: https://www.saucedemo.com
    - Steps: 4
    - Verdict: PASS
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.saucedemo.com")

        # Step 1: FILL Username
        # Selector: input[placeholder="Username"]
        # Strategy: placeholder_attr, Confidence: 0.9
        await page.locator("input[placeholder="Username"]").fill("standard_user")
        # Step 2: FILL Password
        # Selector: input[name="password"]
        # Strategy: name_attr_fuzzy, Confidence: 0.92
        await page.locator("input[name="password"]").fill("secret_sauce")
        # Step 3: CLICK Login
        # Selector: #login-button
        # Strategy: role_name, Confidence: 0.95
        await page.locator("#login-button").click()
        # Step 4: CLICK Add to cart
        # Selector: #add-to-cart-sauce-labs-backpack
        # Strategy: role_name_nth_locator, Confidence: 0.84
        await page.locator("#add-to-cart-sauce-labs-backpack").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_login_simple())