"""
PACTS Generated Test
====================
Requirement ID: saucedemo_login
Generated: 2025-10-30 21:34:25
Verdict: PASS

Discovery Strategies Used:
  - placeholder
  - role_name

"""

import asyncio
from playwright.async_api import async_playwright


async def test_saucedemo_login():
    """
    Test for requirement: saucedemo_login

    Test Details:
    - URL: https://www.saucedemo.com
    - Steps: 3
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.saucedemo.com")

        # Step 1: FILL Username
        # Selector: #user-name
        # Strategy: placeholder, Confidence: 0.88
        await page.locator("#user-name").fill("standard_user")
        # Step 2: FILL Password
        # Selector: #password
        # Strategy: placeholder, Confidence: 0.88
        await page.locator("#password").fill("secret_sauce")
        # Step 3: CLICK Login
        # Selector: #login-button
        # Strategy: role_name, Confidence: 0.95
        await page.locator("#login-button").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_saucedemo_login())