"""
PACTS Generated Test
====================
Requirement ID: wikipedia_search
Generated: 2025-11-02 19:46:11
Verdict: PASS

Discovery Strategies Used:
  - placeholder

"""

import asyncio
from playwright.async_api import async_playwright


async def test_wikipedia_search():
    """
    Test for requirement: wikipedia_search

    Test Details:
    - URL: https://en.wikipedia.org
    - Steps: 2
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://en.wikipedia.org")

        # Step 1: FILL Search Wikipedia
        # Selector: #searchInput
        # Strategy: placeholder, Confidence: 0.88
        await page.locator("#searchInput").fill("Artificial Intelligence")
        # Step 2: PRESS Search Wikipedia
        # Selector: #searchInput
        # Strategy: placeholder, Confidence: 0.88
        await page.locator("#searchInput").press("Enter")
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_wikipedia_search())