"""
PACTS Generated Test
====================
Requirement ID: wikipedia_search
Generated: 2025-11-01 00:59:09
Verdict: PASS

Discovery Strategies Used:
  - mcp_direct_action

"""

import asyncio
from playwright.async_api import async_playwright


async def test_wikipedia_search():
    """
    Test for requirement: wikipedia_search

    Test Details:
    - URL: https://en.wikipedia.org
    - Steps: 2
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://en.wikipedia.org")

        # Step 1: FILL Search Wikipedia
        # Selector: MCP_FILL:Search Wikipedia
        # Strategy: mcp_direct_action, Confidence: 0.95
        await page.locator("MCP_FILL:Search Wikipedia").fill("Artificial Intelligence")
        # Step 2: PRESS Search Wikipedia
        # Selector: MCP_FILL:Search Wikipedia
        # Strategy: mcp_direct_action, Confidence: 0.95
        await page.locator("MCP_FILL:Search Wikipedia").press("Enter")
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_wikipedia_search())