"""
PACTS Generated Test
====================
Requirement ID: amazon_search
Generated: 2025-11-09 02:12:32
Verdict: PASS

Discovery Strategies Used:
  - name_attr_fuzzy

"""

import asyncio
from playwright.async_api import async_playwright


async def test_amazon_search():
    """
    Test for requirement: amazon_search

    Test Details:
    - URL: https://www.amazon.com
    - Steps: 2
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.amazon.com")

        # Step 1: FILL Search
        # Selector: form[name="site-search"]
        # Strategy: name_attr_fuzzy, Confidence: 0.92
        await page.locator("form[name="site-search"]").fill("laptop")
        # Step 2: PRESS Search
        # Selector: form[name="site-search"]
        # Strategy: name_attr_fuzzy, Confidence: 0.92
        await page.locator("form[name="site-search"]").press("Enter")
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_amazon_search())