"""
PACTS Generated Test
====================
Requirement ID: wikipedia_search.txt
Generated: 2025-11-07 21:13:43
Verdict: PASS

Discovery Strategies Used:
  - aria_label

"""

import asyncio
from playwright.async_api import async_playwright


async def test_wikipedia_search_txt():
    """
    Test for requirement: wikipedia_search.txt

    Test Details:
    - URL: https://en.wikipedia.org
    - Steps: 2
    - Verdict: pass
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://en.wikipedia.org")

        # Step 1: FILL Search Wikipedia
        # Selector: input[aria-label="Search Wikipedia"]
        # Strategy: aria_label, Confidence: 0.98
        await page.locator("input[aria-label="Search Wikipedia"]").fill("Artificial Intelligence")
        # Step 2: PRESS Search Wikipedia
        # Selector: input[aria-label="Search Wikipedia"]
        # Strategy: aria_label, Confidence: 0.98
        await page.locator("input[aria-label="Search Wikipedia"]").press("Enter")
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_wikipedia_search_txt())