"""
PACTS Generated Test
====================
Requirement ID: youtube_search
Generated: 2025-11-09 01:51:08
Verdict: PASS

Discovery Strategies Used:
  - ordinal_position
  - placeholder_attr

"""

import asyncio
from playwright.async_api import async_playwright


async def test_youtube_search():
    """
    Test for requirement: youtube_search

    Test Details:
    - URL: https://www.youtube.com
    - Steps: 3
    - Verdict: PASS
    

    Generated by PACTS v1.0
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to target URL
        await page.goto("https://www.youtube.com")

        # Step 1: FILL Search
        # Selector: input[placeholder="Search"]
        # Strategy: placeholder_attr, Confidence: 0.9
        await page.locator("input[placeholder="Search"]").fill("Playwright automation tutorial")
        # Step 2: PRESS Search
        # Selector: input[placeholder="Search"]
        # Strategy: placeholder_attr, Confidence: 0.9
        await page.locator("input[placeholder="Search"]").press("Enter")
        # Step 3: CLICK First Video
        # Selector: [role='link'] >> nth=0
        # Strategy: ordinal_position, Confidence: 0.95
        await page.locator("[role='link'] >> nth=0").click()
        await browser.close()


if __name__ == "__main__":
    asyncio.run(test_youtube_search())