name: PACTS Smoke Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Daily canary at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Manual trigger

env:
  PYTHON_VERSION: '3.11.9'
  PLAYWRIGHT_VERSION: '1.40.0'

jobs:
  smoke-tests:
    name: 5-Site Validation (0 Heals Target)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        test:
          - wikipedia_search
          - github_search
          - amazon_search
          - ebay_search
          - login_simple

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          playwright install chromium --with-deps

      - name: Create .env file
        run: |
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "USE_MCP=true" >> .env
          echo "MCP_ACTIONS_ENABLED=false" >> .env
          echo "HEADLESS=true" >> .env
          echo "SLOW_MO=0" >> .env
          echo "CI=true" >> .env

      - name: Run test - ${{ matrix.test }}
        id: test
        run: |
          python -m backend.cli.main test --req ${{ matrix.test }} --headed=false
        continue-on-error: true

      - name: Retry on failure (once)
        if: steps.test.outcome == 'failure'
        run: |
          echo "Test failed, retrying once..."
          python -m backend.cli.main test --req ${{ matrix.test }} --headed=false

      - name: Collect evidence
        if: always()
        run: |
          mkdir -p evidence/${{ matrix.test }}
          cp screenshots/${{ matrix.test }}*.png evidence/${{ matrix.test }}/ 2>/dev/null || true
          cp generated_tests/test_${{ matrix.test }}.py evidence/${{ matrix.test }}/ 2>/dev/null || true

      - name: Upload evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: evidence-${{ matrix.test }}
          path: evidence/${{ matrix.test }}/
          retention-days: 30

      - name: Check KPIs
        if: success()
        run: |
          echo "✅ Test passed"
          echo "Validating KPIs:"
          echo "  - Heal rounds: Expected 0"
          echo "  - Success rate: Expected 100%"
          echo "  - Step time: Expected <2.5s avg"
          # Add actual KPI extraction from logs if needed

  summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: smoke-tests
    if: always()

    steps:
      - name: Download all evidence
        uses: actions/download-artifact@v4
        with:
          path: evidence/

      - name: Generate summary
        run: |
          echo "## PACTS Smoke Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Test | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
          # Matrix jobs will populate results
          echo "Evidence artifacts uploaded for all tests" >> $GITHUB_STEP_SUMMARY

      - name: Check overall success
        run: |
          if [ "${{ needs.smoke-tests.result }}" == "success" ]; then
            echo "🎉 All tests passed!"
            exit 0
          else
            echo "❌ Some tests failed"
            exit 1
          fi
